version: '3.8'

services:
  app:
    build:
      context: .
      target: ${NODE_ENV:-development}
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
      - ./certs:/app/certs
    ports:
      - "443:443"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - MONGODB_URI=mongodb://mongodb:27017/visitor-analytics
      - NEXT_TELEMETRY_DISABLED=1
      - VERCEL_ANALYTICS_DISABLED=1
      - NEXT_PUBLIC_VERCEL_DEBUG=0
      - NEXT_PUBLIC_SHOW_SPEED_INSIGHTS=false
      - HTTPS=true
      - PORT=443
    depends_on:
      - mongodb
    networks:
      - app-network
    command: npm run dev

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local 